export const GET_CONTACTS = "GET_CONTACTS";
export const GET_CONTACTS_SUCCESS = "GET_CONTACTS_SUCCESS";
export const GET_CONTACTS_FAIL = "GET_CONTACTS_FAIL";

export const GET_CONTACT = "GET_CONTACT";

export const ADD_CONTACT = "ADD_CONTACT";

export const UPDATE_CONTACT = "UPDATE_CONTACT"


