export const GET_CONTACTS = "GET_CONTACTS";
export const GET_CONTACTS_SUCCESS = "GET_CONTACTS_SUCCESS";
export const GET_CONTACTS_FAIL = "GET_CONTACTS_FAIL";




export const GET_ONECONTACT = "GET_ONECONTACT";
export const GET_ONECONTACT_SUCCESS = "GET_ONECONTACT_SUCCESS";
export const GET_ONECONTACT_FAIL = "GET_ONECONTACT_FAIL";